confirm_only_renamed: false

whitelisted_items: [ ]

seconds_before_reset: 5

per_item_confirmation: false

reset_confirm_after_drop: true

blacklisted_worlds: [ ]

messages:
  prefix: "&7[&c&lDropConfirm&7] "
  #use {0} to use seconds before cancel
  cancel_message: "Confirm within {0} seconds!"
  no_permission: "&7You don't have enough permissions!"