confirm_only_renamed: true

whitelisted_items: [ ]

seconds_before_reset: 5

per_item_confirmation: false

reset_confirm_after_drop: true

blacklisted_worlds: [ ]

messages:
  prefix: "&7[&c&lConfirm&7] "
  #use {0} to use seconds before cancel
  cancel_message: "Confirm the drop before {0}s!"
  no_permission: "&7You don't have enough permissions!"