#confirm drops only if items is renamed
confirm_only_renamed: false
#use [] to confirm all drops, use upper case for all items
whitelisted_items: [ ]

seconds_before_reset: 5

per_item_confirmation: false

reset_confirm_after_drop: true

blacklisted_worlds: [ ]

messages:
  prefix: "&7[&c&lConfirmation&7] "
  #use {0} to use seconds before cancel
  cancel_message: "You must confirm the drop do the same thing before {0} seconds !"
  commands:
    incorrect_usage: "&fCorrect Usage : /{0}"
    no_permission: "&cNo Permission !"
    help:
      - "&7&m------------------&8[&6Help Panel&8]&7&m------------------"
      - "{!dropconfirmation.command.reload}&6/dropconfirmation reload &eReload the config"
      - "&6/dropconfirmation info &eDisplay the plugin information"
      - "&7&m----------------------------------------------"