name: DropConfirmation
main: fr.nivcoo.dropconfirmation.DropConfirmation
version: 1.2.0
authors: [ nivcoo ]
api-version: 1.13
commands:
  dropconfirmation:
    description: main command
permissions:
  dropconfirmation.bypass:
    default: op
    description: bypass the drop check
  dropconfirmation.commands:
    default: op
    description: show help
  dropconfirmation.command.reload:
    default: op
    description: reload the plugin