name: DropConfirmation
main: fr.nivcoo.dropconfirmation.DropConfirmation
version: 1.1.6
authors: [nivcoo]
commands:
  dp:
    description: main command
permissions:
  dropconfirmation.bypass:
    default: op
    description: bypass the drop check
  dropconfirmation.reload:
    default: op
    description: reload the plugin