name: DropConfirm
version: @version@
main: com.tamrielnetwork.DropConfirm
api-version: 1.16
authors: [ nivcoo,TamrielNetwork ]
website: https://tamriel.site
description: Prevents Dropping the wrong items.
commands:
  drop:
    description: main command
permissions:
  dropconfirm.bypass:
    default: op
    description: bypass the drop check
  dropconfirm.reload:
    default: op
    description: reload the plugin